name: srdrbk
description: "Sardorbek Abdulabbozov's Personal Website"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  go_router: ^14.2.1
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  responsive_builder: ^0.7.1
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  package_info_plus: ^8.0.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/core/config/localization/
    - assets/images/
    - assets/fonts/
    - assets/vectors/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_18pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter_18pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter_18pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_18pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter_18pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter_18pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter_18pt-BlackItalic.ttf
          weight: 900
          style: italic